name: Run Login Bot

on:
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Install Tesseract OCR
      run: |
        sudo apt update
        sudo apt install -y tesseract-ocr

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Matching ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -d " " -f3 | cut -d "." -f1)

        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")

        wget -N "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"

        unzip chromedriver_linux64.zip

        chmod +x chromedriver

        sudo mv chromedriver /usr/local/bin/

    - name: Run Login Script
      env:
        CGM_USERNAME: ${{ secrets.CGM_USERNAME }}
        CGM_PASSWORD: ${{ secrets.CGM_PASSWORD }}
        CGM_MOBILE: ${{ secrets.CGM_MOBILE }}
      run: |
        python only_login.py
